# 版本号
version: '3'

networks:
  hostnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

# 定义服务
services:
  php.5.6:
    build:
      context: ./php5.6
    volumes:
      - ./../htdocs:/var/www/htdocs
    depends_on:
      - mysql.5.6
    links:
      - mysql.5.6
    ports:
      - 8111:80
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/htdocs
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    networks:
      hostnet:
        ipv4_address: 172.16.238.3

  mysql.5.6:
    build:
      context: ./mysql5.6
    image: mysql:5.6
    networks:
      hostnet:
        ipv4_address: 172.16.238.5
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci'
      ]
    volumes:
      - ./mysql5.6/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yunzhi
      MYSQL_DATABASE: tp5